spring.application.name=Logistics Management API
spring.datasource.url=jdbc:h2:mem:logistics;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.data.redis.repositories.enabled=false
management.health.redis.enabled=false
